ENG-1191
atlasapi/atlas-persistence pull request #367
Opened 2022-05-11 08:32 UTC by IvanKaraslavov

* Improves the already existing findChildrenForParent and findSeriesForBrand methods when resolving content in the MongoContentResolver class by getting only actively published content which is the correct category type in the lookup table so we can perform unpublishing safely 
* Adds new methods for finding the siblings of a content on series and brand level for when unpublishing the whole hierarchy is performed

2022-05-11 10:28 UTC, tristanbeardmore-gray requested changes

2022-05-11 10:28 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/persistence/content/mongo/MongoContentResolver.java
> +    public ResolvedContent findChildrenForParent(String parentUri) {
This method would be slightly cleaner if instead it called a version of the method that did a mongo query using an "or" condition.

2022-05-11 10:28 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/persistence/content/mongo/MongoContentResolver.java
> +            throw new IllegalStateException("The given content is not an episode.");
IllegalArgumentException is more appropriate here.

2022-05-11 10:28 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/persistence/content/mongo/MongoContentResolver.java
> +            throw new IllegalStateException("The given content is not an episode.");
IllegalArgumentException is more appropriate here.

2022-05-11 10:28 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/persistence/content/mongo/MongoContentResolver.java
> +                        .next();
You should check whether you got a result back instead of implicitly erroring here.

2022-05-11 10:28 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/persistence/content/mongo/MongoContentResolver.java
> +                        .next();
You should check whether you got a result back instead of implicitly erroring here.

2022-05-11 10:28 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/persistence/content/mongo/MongoContentResolver.java
> +                                .next();
You should check whether you got a result back instead of implicitly erroring here.

2022-05-11 10:28 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/persistence/content/mongo/MongoContentResolver.java
> +                                .next();
You should check whether you got a result back instead of implicitly erroring here.

2022-05-11 10:28 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/persistence/content/mongo/MongoContentResolver.java
> +                                .next();
Consider simplifying this in some kind of `fetchLookupEntry` method since it's reused a few times and might need some additional logic.

2022-05-11 10:28 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/persistence/content/mongo/MongoContentResolver.java
> +            throw new IllegalStateException("The given content is not a series.");
IllegalArgumentException is more appropriate here.

2022-05-11 10:28 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/persistence/content/mongo/MongoContentResolver.java
> +        String parentUri;
You don't need to define this variable here - it's only ever used in very limited scope before return statements.

2022-05-11 10:28 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/persistence/content/mongo/MongoContentResolver.java
> +                                findChildrenForParent(parentUri, true), model);
Use convenient methods to avoid 'magic' booleans where possible.
e.g.:
```
findChildrenForTopLevelParent(String parentUri) {
  return findChildrenForParent(parentUri, true);
}

findChildrenForNonTopLevelParent(String parentUri) {
  return findChildrenForParent(parentUri, false);
}
```

2022-05-11 10:28 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/persistence/content/mongo/MongoContentResolver.java
> +        addIdsToResults(res);
I don't think this is needed since it's done within `findChildrenForParent` and isn't a cheap operation.

2022-05-11 10:28 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/persistence/content/mongo/MongoContentResolver.java
> +    private ResolvedContent findSiblingsForContent(
Split this method into two; one for `PROGRAMME_GROUP` and one for `CHILD_ITEM` to avoid the branching logic and nonsensical method parameter `isBrandLevel` for the `PROGRAMME_GROUP` case.

2022-05-13 15:07 UTC, tristanbeardmore-gray requested changes

2022-05-17 09:52 UTC, tristanbeardmore-gray reviewed
New changes seem fine

2022-05-17 16:29 UTC, EmiEnache commented on src/main/java/org/atlasapi/persistence/content/mongo/MongoContentResolver.java
> +    private ResolvedContent findSiblingsForChildren(String episodeUri, boolean isBrandLevel) {
Not convinced on the "isBrandLevel" name, since it's about something relative to the "subject" episode that we're checking, as opposed to the subject itself... but not sure what would be better. Maybe "onBrandLevel"? Maybe it's fine as is.

2022-05-18 09:39 UTC, merged